### ISSUE TITLE
Flutter web does not recognize Firebase.initializeApp()

### ISSUE THREAD

**Issue by abdelrahmanmagdii** [fluttercommunity/admin_dashboard#5]
When using flutter build web, the console says that Firebase.initializeApp() has not been called although it is being called both in main.dart and in index.html.

**Comment by Hirdey-1999** [comment]
Check Out This Solution https://stackoverflow.com/questions/63492211/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in

**Comment by abdelrahmanmagdii** [comment]
Thanks for your reply! Turns out the issue was flutter web had an error retrieving the Firebase app which was being created in the main, I got it working by passing the firebase app and creating the authentication using a factory method instead of FirebaseAuth.instance. Cheers!
